name: Auto Commit Tasks

on:
  schedule:
    - cron: '0 11,15,18,20 * * *'  # 4 раза в день по UTC (14, 18, 21, 23:30 МСК)
  workflow_dispatch:                # возможность ручного запуска

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run autocommit script
        run: |
          chmod +x other_tasks/autocommit.sh
          bash other_tasks/autocommit.sh
